export const categories = [
  { id: "1", name: "Fresh Milk", icon: "🥛", slug: "milk", count: 12 },
  { id: "2", name: "Cheese", icon: "🧀", slug: "cheese", count: 18 },
  { id: "3", name: "Butter", icon: "🧈", slug: "butter", count: 8 },
  { id: "4", name: "Yogurt", icon: "🫙", slug: "yogurt", count: 15 },
  { id: "5", name: "Cream", icon: "🍦", slug: "cream", count: 10 },
  { id: "6", name: "Ice Cream", icon: "🍨", slug: "ice-cream", count: 22 },
];

export const products = [
  {
    id: "1",
    name: "Full Cream Milk",
    price: 2.99,
    originalPrice: 3.49,
    category: "milk",
    categoryName: "Fresh Milk",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop",
    description: "Fresh full cream milk sourced from local farms. Rich in calcium and vitamins, perfect for the whole family.",
    type: "fresh",
    weight: "1 Litre",
    inStock: true,
    rating: 4.8,
    reviews: 124,
    badge: "Best Seller",
  },
  {
    id: "2",
    name: "Organic Greek Yogurt",
    price: 3.49,
    originalPrice: null,
    category: "yogurt",
    categoryName: "Yogurt",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop",
    description: "Thick, creamy organic Greek yogurt with live cultures. High in protein and probiotics.",
    type: "organic",
    weight: "500g",
    inStock: true,
    rating: 4.6,
    reviews: 89,
    badge: "Organic",
  },
  {
    id: "3",
    name: "Aged Cheddar Cheese",
    price: 5.99,
    originalPrice: 6.99,
    category: "cheese",
    categoryName: "Cheese",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop",
    description: "Mature aged cheddar with a sharp, rich flavor. Perfect for cooking or a cheese board.",
    type: "aged",
    weight: "250g",
    inStock: true,
    rating: 4.9,
    reviews: 203,
    badge: "Premium",
  },
  {
    id: "4",
    name: "Salted Butter",
    price: 2.49,
    originalPrice: null,
    category: "butter",
    categoryName: "Butter",
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&h=400&fit=crop",
    description: "Creamy salted butter made from high-quality cream. Ideal for spreading and cooking.",
    type: "salted",
    weight: "250g",
    inStock: true,
    rating: 4.7,
    reviews: 156,
    badge: null,
  },
  {
    id: "5",
    name: "Fresh Cream",
    price: 1.99,
    originalPrice: 2.49,
    category: "cream",
    categoryName: "Cream",
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=400&h=400&fit=crop",
    description: "Fresh whipping cream, perfect for desserts and sauces.",
    type: "fresh",
    weight: "250ml",
    inStock: true,
    rating: 4.5,
    reviews: 67,
    badge: "Sale",
  },
  {
    id: "6",
    name: "Vanilla Ice Cream",
    price: 4.99,
    originalPrice: null,
    category: "ice-cream",
    categoryName: "Ice Cream",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=400&fit=crop",
    description: "Classic vanilla ice cream made with real vanilla beans and fresh cream.",
    type: "classic",
    weight: "500ml",
    inStock: true,
    rating: 4.8,
    reviews: 312,
    badge: "Popular",
  },
  {
    id: "7",
    name: "Skimmed Milk",
    price: 2.49,
    originalPrice: null,
    category: "milk",
    categoryName: "Fresh Milk",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop",
    description: "Low-fat skimmed milk, great for those watching their calorie intake.",
    type: "skimmed",
    weight: "1 Litre",
    inStock: true,
    rating: 4.3,
    reviews: 78,
    badge: null,
  },
  {
    id: "8",
    name: "Mozzarella Cheese",
    price: 3.99,
    originalPrice: 4.49,
    category: "cheese",
    categoryName: "Cheese",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop",
    description: "Fresh mozzarella, perfect for pizza, salads and sandwiches.",
    type: "fresh",
    weight: "200g",
    inStock: false,
    rating: 4.6,
    reviews: 145,
    badge: "Sale",
  },
];

export const orders = [
  {
    id: "ORD-2026-001",
    items: [
      { productId: "1", name: "Full Cream Milk", qty: 2, price: 2.99 },
      { productId: "3", name: "Aged Cheddar Cheese", qty: 1, price: 5.99 },
    ],
    status: "delivered",
    date: "2026-03-18",
    total: 11.97,
    address: "123 Green Street, Freshville",
    deliveryAgent: "John Doe",
  },
  {
    id: "ORD-2026-002",
    items: [
      { productId: "2", name: "Organic Greek Yogurt", qty: 3, price: 3.49 },
      { productId: "4", name: "Salted Butter", qty: 1, price: 2.49 },
    ],
    status: "out_for_delivery",
    date: "2026-03-22",
    total: 12.96,
    address: "456 Dairy Lane, Milktown",
    deliveryAgent: "Jane Smith",
  },
  {
    id: "ORD-2026-003",
    items: [
      { productId: "6", name: "Vanilla Ice Cream", qty: 2, price: 4.99 },
    ],
    status: "processing",
    date: "2026-03-23",
    total: 9.98,
    address: "789 Cream Avenue, Butterville",
    deliveryAgent: null,
  },
  {
    id: "ORD-2026-004",
    items: [
      { productId: "1", name: "Full Cream Milk", qty: 4, price: 2.99 },
      { productId: "5", name: "Fresh Cream", qty: 2, price: 1.99 },
    ],
    status: "pending",
    date: "2026-03-23",
    total: 15.94,
    address: "321 Farm Road, Dairyton",
    deliveryAgent: null,
  },
];

export const users = [
  { id: "1", name: "Alice Johnson", email: "alice@example.com", phone: "+1 555-0101", orders: 12, joined: "2025-01-15", status: "active" },
  { id: "2", name: "Bob Smith", email: "bob@example.com", phone: "+1 555-0102", orders: 5, joined: "2025-03-20", status: "active" },
  { id: "3", name: "Carol Davis", email: "carol@example.com", phone: "+1 555-0103", orders: 28, joined: "2024-11-08", status: "active" },
  { id: "4", name: "David Wilson", email: "david@example.com", phone: "+1 555-0104", orders: 0, joined: "2026-02-10", status: "inactive" },
  { id: "5", name: "Eva Martinez", email: "eva@example.com", phone: "+1 555-0105", orders: 9, joined: "2025-06-30", status: "active" },
];

export const deliveryAgents = [
  { id: "1", name: "John Doe", phone: "+1 555-0201", email: "john@dairy.com", zone: "North", activeOrders: 3, completed: 142, status: "active", rating: 4.9 },
  { id: "2", name: "Jane Smith", phone: "+1 555-0202", email: "jane@dairy.com", zone: "South", activeOrders: 2, completed: 98, status: "active", rating: 4.7 },
  { id: "3", name: "Mike Brown", phone: "+1 555-0203", email: "mike@dairy.com", zone: "East", activeOrders: 0, completed: 201, status: "offline", rating: 4.8 },
  { id: "4", name: "Sarah Lee", phone: "+1 555-0204", email: "sarah@dairy.com", zone: "West", activeOrders: 1, completed: 67, status: "active", rating: 4.6 },
];

export const testimonials = [
  {
    id: "1",
    name: "Emily Chen",
    role: "Regular Customer",
    avatar: "EC",
    rating: 5,
    comment: "DairyFresh has completely transformed my morning routine. The milk is incredibly fresh and delivered right to my door. Couldn't be happier!",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    role: "Chef & Food Blogger",
    avatar: "MJ",
    rating: 5,
    comment: "As a professional chef, quality dairy is everything. DairyFresh delivers the best artisan cheese and cream I've ever cooked with. Absolutely outstanding!",
  },
  {
    id: "3",
    name: "Priya Patel",
    role: "Nutritionist",
    avatar: "PP",
    rating: 5,
    comment: "I recommend DairyFresh to all my clients. Their organic yogurt and milk are perfect for health-conscious families. Amazing quality and taste!",
  },
];

export const cartItems = [
  { id: "1", productId: "1", name: "Full Cream Milk", price: 2.99, qty: 2, weight: "1 Litre", image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=100&h=100&fit=crop" },
  { id: "2", productId: "3", name: "Aged Cheddar Cheese", price: 5.99, qty: 1, weight: "250g", image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=100&h=100&fit=crop" },
  { id: "3", productId: "2", name: "Organic Greek Yogurt", price: 3.49, qty: 2, weight: "500g", image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=100&h=100&fit=crop" },
];
